{
 "title": "mle-pr-final",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Онлайн рекомендации",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "app_counter_online_rec_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Общее количество запросов к сервису",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Оффлайн рекомендации",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "app_counter_offline_rec_total", "legendFormat": "__auto" }
   ]
  }
 ]
}