FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY ml_service/ ./ml_service/

ENV MAIN_APP_PORT=8000

EXPOSE ${MAIN_APP_PORT}

# CMD uvicorn service.main:app --port ${MAIN_APP_PORT} --host 0.0.0.0